// GENERATED by apps/api/scripts/export_sdui_schema.py — do not edit by hand.
// Source of truth: apps/api/superapp/sdui/blocks.py

export const SDUI_VERSION = 1;

export type TextBlock = {
  type: "text";
  text: string;
  variant?: "body" | "title" | "subtitle" | "caption";
};

export type InsightCard = {
  type: "insight_card";
  id: string;
  agent: string;
  title: string;
  body: string;
  emphasis?: "default" | "positive" | "warning";
  action_label?: string | null;
  action_id?: string | null;
};

export type Stat = {
  label: string;
  value: string;
  delta?: string | null;
  unit?: string | null;
};

export type StatRow = {
  type: "stat_row";
  stats: Stat[];
};

export type ImageCard = {
  type: "image_card";
  image_url: string;
  title?: string | null;
  subtitle?: string | null;
};

export type ListItem = {
  id: string;
  title: string;
  subtitle?: string | null;
  trailing?: string | null;
};

export type ListBlock = {
  type: "list";
  items: ListItem[];
};

export type GridImage = {
  id: string;
  image_url: string;
  label?: string | null;
};

export type ImageGrid = {
  type: "image_grid";
  items: GridImage[];
  columns?: 2 | 3 | 4;
};

export type OutfitItem = {
  garment_id: string;
  image_url?: string | null;
  label: string;
};

export type OutfitCard = {
  type: "outfit_card";
  id: string;
  agent: string;
  title: string;
  occasion?: string | null;
  rationale: string;
  items: OutfitItem[];
};

export type AgentStat = {
  n: string;
  label: string;
  accent?: boolean;
};

export type AgentCard = {
  type: "agent_card";
  id: string;
  agent: string;
  name: string;
  sub: string;
  live?: boolean;
  headline: string;
  body: string;
  stats?: AgentStat[];
  screen?: string | null;
};

export type AgentGridItem = {
  screen: string;
  name: string;
  sub: string;
  tone?: "indigo" | "mint" | "amber" | "rose";
};

export type AgentGrid = {
  type: "agent_grid";
  items: AgentGridItem[];
};

export type DraftCard = {
  type: "draft_card";
  id: string;
  agent: string;
  from_name: string;
  subject: string;
  why: string;
  draft: string;
  status?: "waiting" | "edited" | "sent" | "dismissed";
  deferred_label?: string | null;
  why_detail?: string | null;
};

export type TimelineItem = {
  text: string;
  verdict: string;
  tone?: "ask" | "did" | "filed";
  at: string;
};

export type Timeline = {
  type: "timeline";
  items: TimelineItem[];
  footer?: string | null;
};

export type Action = {
  id: string;
  label: string;
  style?: "primary" | "secondary" | "destructive";
};

export type ActionRow = {
  type: "action_row";
  actions: Action[];
};

export type LeafBlock = TextBlock | InsightCard | StatRow | ImageCard | ListBlock | ImageGrid | OutfitCard | AgentCard | AgentGrid | DraftCard | Timeline | ActionRow;

export type Section = {
  type: "section";
  title?: string | null;
  blocks: LeafBlock[];
};

export type Screen = {
  type: "screen";
  theme?: "light" | "dark";
  version?: number;
  title: string;
  sections: Section[];
};
