"""Export the SDUI contract from its single source of truth (blocks.py):

- packages/sdui-schema/schema.json       JSON Schema of Screen
- apps/mobile/src/sdui/types.ts          generated TypeScript types (do not edit)

Run from apps/api:   PYTHONPATH=. python scripts/export_sdui_schema.py
CI drift check:      PYTHONPATH=. python scripts/export_sdui_schema.py --check
"""
import json
import sys
import types as pytypes
from pathlib import Path
from typing import Annotated, Literal, Union, get_args, get_origin

from pydantic import BaseModel

from superapp.sdui import blocks
from superapp.sdui.blocks import Screen

SDUI_VERSION = Screen.model_fields["version"].default

# Emission order (dependencies first). LeafBlock is the named discriminated union.
MODELS: list[type[BaseModel]] = [
    blocks.TextBlock,
    blocks.InsightCard,
    blocks.Stat,
    blocks.StatRow,
    blocks.ImageCard,
    blocks.ListItem,
    blocks.ListBlock,
    blocks.Action,
    blocks.ActionRow,
]
POST_UNION_MODELS: list[type[BaseModel]] = [blocks.Section, blocks.Screen]


def ts_type(ann) -> str:
    if ann is blocks.LeafBlock:
        return "LeafBlock"
    origin = get_origin(ann)
    if origin is Annotated:
        return ts_type(get_args(ann)[0])
    if ann is str:
        return "string"
    if ann in (int, float):
        return "number"
    if ann is bool:
        return "boolean"
    if ann is dict:
        return "Record<string, unknown>"
    if origin is Literal:
        return " | ".join(json.dumps(a) for a in get_args(ann))
    if origin is list:
        inner = ts_type(get_args(ann)[0])
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if origin in (Union, pytypes.UnionType):
        return " | ".join(
            "null" if a is type(None) else ts_type(a) for a in get_args(ann)
        )
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return ann.__name__
    raise TypeError(f"No TS mapping for annotation {ann!r}")


def emit_model(model: type[BaseModel]) -> str:
    lines = [f"export type {model.__name__} = {{"]
    for name, f in model.model_fields.items():
        # The server serializes defaults, so fields are always present on the
        # wire; `?` marks defaulted fields anyway so hand-built test fixtures
        # stay light. The `type` discriminator stays required for narrowing.
        optional = "" if (f.is_required() or name == "type") else "?"
        lines.append(f"  {name}{optional}: {ts_type(f.annotation)};")
    lines.append("};")
    return "\n".join(lines)


def generate_types_ts() -> str:
    leaf_names = [m.__name__ for m in get_args(get_args(blocks.LeafBlock)[0])]
    parts = [
        "// GENERATED by apps/api/scripts/export_sdui_schema.py — do not edit by hand.",
        "// Source of truth: apps/api/superapp/sdui/blocks.py",
        "",
        f"export const SDUI_VERSION = {SDUI_VERSION};",
        "",
        *[emit_model(m) + "\n" for m in MODELS],
        "export type LeafBlock = " + " | ".join(leaf_names) + ";",
        "",
        *[emit_model(m) + "\n" for m in POST_UNION_MODELS],
    ]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    outputs = {
        root / "packages" / "sdui-schema" / "schema.json": json.dumps(
            Screen.model_json_schema(), indent=2
        )
        + "\n",
        root / "apps" / "mobile" / "src" / "sdui" / "types.ts": generate_types_ts(),
    }

    if "--check" in sys.argv:
        stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
        for p in stale:
            print(f"STALE: {p} — rerun scripts/export_sdui_schema.py", file=sys.stderr)
        return 1 if stale else 0

    for p, content in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
